### ISSUE TITLE
Fix 'import *' in Python code

### ISSUE THREAD

**Issue by lb324567** [gchq/gaffer-tools#1031]
Using import * is discouraged, explicit imports should be used as it improves readability and can add unnecessary difficulties when the namespace gets polluted with loads of functions and classes that aren't being used.

This ticket is to, where sensible, remove the implicit imports and make them explicit.

**Comment by t92549** [comment]
When used to import generated code, this must be done: https://github.com/gchq/gaffer-tools/blob/423b9f2ddebc612d0a0a5ca9a3557807030e3c9a/python-shell/src/gafferpy/gaffer_operations.py#L669

There is also the `gaffer.py` file which acts as a helper/__init__.py: https://github.com/gchq/gaffer-tools/blob/423b9f2ddebc612d0a0a5ca9a3557807030e3c9a/python-shell/src/gafferpy/gaffer.py#L56

However, there are a couple of places outside these that import from `gaffer_core` that could be tidied.

**Comment by thomaskroi1996** [comment]
Hello! Can you please assign this to me? Would love to work on it!

**Comment by t92549** [comment]
I think, as described, it's not possible to change this due to the nature of the generated code so I will be closing this issue
