### ISSUE TITLE
Extend autogeneration of Gaffer Operations by gafferpy/fishbowl to include Gaffer Spark Operations

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-tools#1062]
Gaffer Spark Operations appear to be in a separate category to "normal" Operations and the autogeneration of python equivalents doesn't include them yet.

**Comment by t92549** [comment]
In order for this to happen, the spark-library would need to be included in the [classpath](https://github.com/gchq/Gaffer/blob/382d6898058dfbdb8aa039194245f9dfa3f466f9/rest-api/spring-rest/pom.xml#L42) for the rest jar in core Gaffer.

**Comment by t92549** [comment]
This would happen automatically if https://github.com/gchq/Gaffer/issues/2941 was done
