### ISSUE TITLE
Add pylint/PEP8 checks to GitHub Actions to validate the python shell

### ISSUE THREAD

**Issue by p013570** [gchq/gaffer-tools#137]
Travis should run some code analysis checks to determine whether the Python shell is ready for release, e.g. pylint/PEP8.

**Comment by t92549** [comment]
Some linting on the Python shell would be nice to ensure code quality

**Comment by t92549** [comment]
Currently there are lots of inconsistent uses of " and ' for Strings, as well as lines that are very long. A PUP8 linter would flag these.

**Comment by t92549** [comment]
Fixed by https://github.com/gchq/gaffer-tools/pull/1028
