### ISSUE TITLE
Allow multiple seeds to be added to the UI at once

### ISSUE THREAD

**Issue by p013570** [gchq/gaffer-tools#156]
Instead of adding each seed one at a time, it would be useful to add multiple seeds, e.g

Select vertex type - e.g road traffic 'junction'.

Then paste into a box:
M5:9
M5:10
M5:24
M5:28

**Comment by d47853** [comment]
When you click "add seeds", you can tick a check box for multiple seeds. This allows you to enter seeds like the example above. For complex seeds, you would use comma separated fields. For example an array of TypeSubTypeValues would look like:

**Comment by d47853** [comment]
T,ST,V
T1,ST1,V1
T2,ST2,V2

**Comment by p013570** [comment]
Merged into develop.
