### ISSUE TITLE
Develop utility to autogenerate Slider config

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-tools#157]
When we test the performance of Gaffer (see #50), we plan to deploy it onto clusters of varying sizes. Rather than having to manually create appConfig.json and resources.json files to size each tablet server appropriately for each cluster, can we develop a utility that will interrogate a YARN cluster to find out what resources are available and then autogenerate the config instead?

**Comment by gaffer01** [comment]
Merged into develop.
