### ISSUE TITLE
Allow Gaffer to be deployed onto Accumulo 1.8.0+ via Slider

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-tools#195]
The [Accumulo application package](https://github.com/apache/incubator-slider/tree/develop/app-packages/accumulo) that we use currently fails to build for Accumulo 1.8.0+. This has been logged as an issue with the Slider project ([SLIDER-1249](https://issues.apache.org/jira/browse/SLIDER-1249)).

Whilst we wait for the issue to be resolved, we can patch the code base ourselves when we build the application package.

**Comment by gaffer01** [comment]
Merged into develop.
