### ISSUE TITLE
Add Python checks to Travis

### ISSUE THREAD

**Issue by t616178** [gchq/gaffer-tools#20]
Travis should run some checks to determine whether the Python shell is ready for release (unit tests, pylint/PEP8 checks etc)

**Comment by p013570** [comment]
I've added config to travis to run all python tests. This has been merged into develop.

I will leave this issue open as we still need to write some more tests.

**Comment by p013570** [comment]
We haven't added any pylint/PEP8 checks, I have opened a separate issue to do that https://github.com/gchq/gaffer-tools/issues/137.

**Comment by p013570** [comment]
Merged into develop.
