### ISSUE TITLE
Add 'public' visibility to AWS integration test template

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-tools#218]
A new integration test has been added to Gaffer which requires an additional Accumulo visibility:
[SchemaHidingIT](https://github.com/gchq/Gaffer/blob/develop/core/graph/src/test/java/uk/gov/gchq/gaffer/integration/graph/SchemaHidingIT.java) requires a "public" visibility

**Comment by p013570** [comment]
Merged into develop.
