### ISSUE TITLE
Update accumulo to 1.8.1 in mini-accumulo-cluster

### ISSUE THREAD

**Issue by 6487927a** [gchq/gaffer-tools#242]
Currently the mini-accumulo-cluster module is using an old version of accumulo, 1.6.5, when the gaffer docs mention that it was [extensively tested on 1.8.1](https://gchq.github.io/gaffer-doc/stores/accumulo-store.html#accumulo-set-up).

**Comment by p013570** [comment]
# Migration Steps
This only applies to you if you are using the mini-accumulo-store.

You shouldn't need to do any migration, but it is worth noting that the version of accumulo used for the mini accumulo store has been updated to 1.8.1, inline with the the accumulo version for the rest of Gaffer.

**Comment by p013570** [comment]
Merged into develop.
