### ISSUE TITLE
Create query page

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#251]
Create a query page which will:

1. select an operation
2. customise the view if applicable
3. fill in parameters if applicable
4. execute the operation

This should be a single page - not split up with tabs.
It should go through much the same steps and have a similar feel to the query builder (minus the tabs). Feel free to rip code from the query builder to complete this page.

**Comment by d47853** [comment]
You should also remove the button and query building dialog as part of this issue

**Comment by p013570** [comment]
Merged into develop.

**Comment by d47853** [comment]
Will fix handling non iterables on different branch
