### ISSUE TITLE
Add URL querying

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#256]
It would be good to open the UI and instantly run a query.

something like: http://hostname:8443/graph?operation=GetElements&input=M5,M4,M32

The navigation service or routing config could intercept the query string, execute a gaffer operation and redirect you to the graph view.

**Comment by p013570** [comment]
URL query parameters:
- operation
- input
- parameters
- startDate
- endDate

**Comment by p013570** [comment]
Merged into develop.
