### ISSUE TITLE
Fix nav bar for all pages

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#258]
All views except the graph view, the nav bar can be scrolled out of view. 

To permanently allow access to the nav bar, the div surrounding the ng-view element should be changed for an md-content element. Remove nested md-content elements:

index.html: 

from
```
<div>
    <ng-view></ng-view>
</div>
```

to
```
<md-content>
    <ng-view></ng-view>
</md-content>
```

graph.html:

from
```
<md-content>
...
</md-content>
```

to
```
<div>
...
</div
```

**Comment by d47853** [comment]
# Migration Steps

Whereas before you may have had a parent md-content element in your view (ie graph view, raw view, settings view etc), you should now use a div. This is to avoid nested scrollbars.

**Comment by p013570** [comment]
Merged into develop.
