### ISSUE TITLE
Make UI get operations async

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#261]
Currently the get operations on most of our services are synchronous. This means that the controller is responsible for calling the functions once things are loaded in the correct order.

We could do away with the controller and use angular's $q library to run the get operations asynchronously. This would mean that the web app is using up to date information and would mean that load and initialise methods could be removed.

In some cases we could store the retrieved data to avoid repeating $http calls. This should result in a performance boost and reduced lag time at the start, as well as simplify code.

See https://docs.angularjs.org/api/ng/service/$q for how to use $q

Essentially we will go from:
```
var someVar;

service.get = function() {
    return someVar;
}

service.load = function() {
    $http.get('some/endpoint')
        .success(function(response) {
            someVar = response;
        });
}
```

to something more like:
```
var someVar;

service.get = function() {
    var defer = $q.defer();
    if(!someVar) {
        $http.get('some/endpoint')
            .success(function(response) {
                someVar = response;
                defer.resolve(someVar);
            });
    } else {
        defer.resolve(someVar)
    }
    
    return defer.promise;
}
```

**Comment by d47853** [comment]
# Migration steps

Developers should be aware that where before, you could access the config using config.get(), this function now returns a promise. 

You'll need to migrate your synchronous code:
```
var myConfig = config.get();
// do stuff with myConfig
```

to Asynchronous:
```
config.get().then(function (myConfig) {
    // do stuff with myConfig
});
```

You'll need to do the same for the schema.

**Comment by p013570** [comment]
Merged into develop.
