### ISSUE TITLE
Make nav bar more dynamic

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#262]
Currently the nav bar is static with all the routes hard-coded into the HTML. It would be good to extract these routes into the navigation service. 

If we can, we should use the route config (which tells angular what route correlates to which view) to dynamically populate the service variable. This would mean that a developer can just change the routes according to what pages they want to display (or even add their own) and the nav bar will just pick them up automatically.

**Comment by p013570** [comment]
No longer required.
