### ISSUE TITLE
Unit test query page, nav bar and graph components

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#266]
Controllers contain business logic that needs testing. Use the test framework configured in #264 to achieve this

**Comment by d47853** [comment]
Added tests for the following components: 

* The Query Page
* View Builder
* Operation selector
* Graph
* Selected Elements viewer
* Loading Circle
* Nav Bar
* View Builder
* Seed Manager
* Result Count warning dialog

**Comment by p013570** [comment]
Merged into develop.
