### ISSUE TITLE
Operation chain builder in UI

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#287]
Instead of executing an operation, we should give the user the option to add an operation to a chain. 

The user should then be able to select another operation, configure it's input/view/parameters, although the input is only optional as normally the output from the previous operation is used as the input to the next. The user should be able to see all the operations in the chain somehow and edit each one. 

The user should then be able to execute this operation chain.

**Comment by p013570** [comment]
Merged into develop.
