### ISSUE TITLE
Improve seed builder UX

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#312]
Make inline seed builders forms so that when a user presses enter their seeds get added. Furthermore, it is currently unclear whether or not a user has added seeds. There should be a message stating that no seeds are added.

Also add tooltips to buttons so it's obvious what each one does.
Remove from card to save space reduce clunkiness.
Remove 'vertexType' from the app since it adds a layer of unwanted complexity.

**Comment by p013570** [comment]
Merged into develop.
