### ISSUE TITLE
Populate available operations by default

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#319]
Use the config to populate the available operations on startup without calling reload named operations.

**Comment by d47853** [comment]
## Migration Steps

If a developer wishes to not load the NamedOperations on startup, they must set the operations.loadOnStartup flag to true in the config. For Example:

```
{
  "operations": {
    "loadOnStartup": false
  }
}
```

If the developer forgets to set the flag or sets it to true, the Named Operations will be loaded, as long as the Named Operations are supported by the store.

**Comment by p013570** [comment]
Merged into develop.
