### ISSUE TITLE
Unable to deploy CloudFormation templates when Gaffer versions are specified as commit hashes

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-tools#343]
A number of the CloudFormation templates need to build Gaffer and Gaffer Tools from source. This used to be performed by cloning the repos and then checking out the release/branch/commit that the user specified. However, this meant the entire repo's history was downloaded each time. To speed up this process we switched to shallow clones. Although this works fine when a version of Gaffer is specified as a tagged release or branch name, it does not work for commit hashes.

Investigate switching to using GitHub's archive download links, rather than cloning repos using git. These links provide zip files of the repo, which are roughly equivalent to a shallow clone, and can be requested for tagged releases, branches and commit hashes.

**Comment by p013570** [comment]
Merged into develop.
