### ISSUE TITLE
Unit test raw and settings components

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#348]

**Comment by g609bmsma** [comment]
Just looking for a bit of clarity on this issue - as far as I can tell, the settings component already has a corresponding unit test - does raw still want one writing, or was this done and not removed, with a decision made to leave the component test-less?

**Comment by d47853** [comment]
This is an old issue and is probably no longer valid. As you pointed out, the settings component already has tests. The raw view may be removed or enhanced, as per #575. If it is enhanced, I would expect unit tests to be included in the issue.
