### ISSUE TITLE
Unable to deploy Migration Test on AWS if the Gaffer versions are specified as commit hashes

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-tools#358]
The source code for AWS Lambda functions can only be specified inside a CloudFormation template if it [does not exceed 4096 characters](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile).

Commit hashes are 40 characters long and are currently substituted into the lambda function in the Migration Testing template 11 times. This adds an extra 440 characters to the source code, resulting in the code breaching this limit and preventing the template from being deployed.

The code for the Lambda function will need to be refactored to ensure it does not breach the limit when commit hashes are used.

**Comment by ctas582** [comment]
https://github.com/gchq/gaffer-tools/commit/09402eb5ae8d2e4aacf616116d973de18494eb0d reduces the character count from 4112 to 3357, when commit hashes are used for all Gaffer and gaffer-tools versions

**Comment by p013570** [comment]
Merged into develop.
