### ISSUE TITLE
Expose Maven Failsafe test results when run on AWS

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-tools#361]
The deployment of the integration testing CloudFormation template succeeds / fails according to whether the Accumulo store integration tests pass / fail. If it fails, the only way to find out which tests are failing is to SSH directly into the EMR cluster and check the logs for the step scripts.

Can the test results be exposed so users don't need to SSH into the cluster? Can we integrate with [SNS](https://aws.amazon.com/sns/) so that users can customise how they receive the results?

**Comment by ctas582** [comment]
I've expanded this issue to cover exposing results that are run by the integration, system and migration testing CloudFormation templates.

**Comment by gaffer01** [comment]
Merged into develop.
