### ISSUE TITLE
Change "entities" for "entity types" on custom filter

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#410]
From feedback on the UI, the labels on the two drop-downs (Only include these entities/edges) are confusing and don't really convey the right message. Really we're narrowing down the element group (or type). The label on the drop-downs should reflect this.

**Comment by g609bmsma** [comment]
Hello, would anyone mind if I had a go at this? Had a quick look and, far as I can tell, the only files that would need any changes are view-builder.html, view-builder-component-spec.js and (potentially?) view-builder-component.js?

**Comment by d47853** [comment]
Yeah that's correct

**Comment by d47853** [comment]
Merged into develop
