### ISSUE TITLE
UI doesn't handle Graphs with different vertex types

### ISSUE THREAD

**Issue by p013570** [gchq/gaffer-tools#411]
A single Gaffer graph can have different types of vertices as long as a single serialiser is provided that can handle all of the different types. When entering the seeds for a query in the UI, it just uses the first vertex it finds in the schema to determine what the type of seed is.

If there are multiple vertex types, we would need an option in the UI to allow a user to choose the class type of seed. 

This is low priority as we haven't really tested Gaffer with different types of vertices and it isn't something we are aware anyone is currently doing.

**Comment by p013570** [comment]
Linked to #398

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
