### ISSUE TITLE
Update python-shell with new additions

### ISSUE THREAD

**Issue by m607123** [gchq/gaffer-tools#425]
With the release of Gaffer 1.4.0 and Koryphe 1.3.0, there will be a number of new functions, predicates, and operations, which will require adding to the Python Shell.
These will be:
`If` : gchq/koryphe#81
`IsLongerThan` : gchq/koryphe#89
`Length` : gchq/koryphe#85

`ExtractId` and `ExtractProperty` : gchq/Gaffer#1705
`If` : gchq/Gaffer#1649

**Comment by p013570** [comment]
Merged into develop.
