### ISSUE TITLE
Support composite types in the type service

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#432]
The type service should support composite types such as TreeSets, HashMaps and ArrayLists as well as standard arrays. 

They should be incorporated into the type service and should be generic (ie the type service should not store "java.util.ArrayList<java.lang.String>" as a type)

They should also be supported by the dynamic input component possibly using md-chips.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
