### ISSUE TITLE
Update Python Shell with new additions

### ISSUE THREAD

**Issue by m607123** [gchq/gaffer-tools#452]
This update should include new Operations that will be released in Gaffer v1.5.0:
`While`: gchq/Gaffer#1669
`ExtractGroup`: gchq/Gaffer#1735

**Comment by m607123** [comment]
This can be retroactively updated with any further additions to Gaffer v1.5.0 and/or Koryphe v1.4.0 .

**Comment by t92549** [comment]
Removing this milestone as this is a continuous issue

**Comment by n3101** [comment]
@t92549 As we have decided not to develop  gafferpy in Gaffer 2.0, presumably this issue can now be closed?

**Comment by t92549** [comment]
This can be closed as Gafferpy 2/fishbowl or whatever we call it, will be dynamic and won't need manual updates. Also, as far as I am aware we don't plan to keep updating the old Python shell
