### ISSUE TITLE
Unable to set heap size on Mini Accumulo Cluster

### ISSUE THREAD

**Issue by javadev001001** [gchq/gaffer-tools#466]
Added the ability to specify the memory heap size of a MiniAccumuloCluster instance using the instance.heap.size property specified in a properties file, rather than passing arguments to the MiniAccumuloClusterController constructor.  This allows all parameters that were previously constructor args to be passed to the cluster using a properties file instead.

Users can construct instance of the MiniAccumuloClusterController or MiniAccumuloClusterWithShellController using the .buildFromProps method in the Builder, having specified a properties file.

**Comment by p013570** [comment]
Merged into develop.
