### ISSUE TITLE
Incorrect sorting of dates

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#472]
Date properties in the table are displayed as their human readable date format. However this means that when sorted, the table sorts using alphabetical order as opposed to sorting by time.

This means that that sorting in ascending order (earliest first) would produce:

* 02/07/2014
* 12/05/2015
* 30/06/2010

As opposed to:

* 30/06/2010
* 02/07/2014
* 12/05/2015

**Comment by p013570** [comment]
Done as part of #506.
