### ISSUE TITLE
Add setting to clear operation chain after each execution

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#481]
Sometimes a user will want to clear the operation chain after they run it. However it would be frustrating if a user wants to run similar queries each time if they have to keep rebuilding a complex chain. 

There should be an option to reset the operation chain once executed. It should not reset when an operation is executed on it's own. By default, it should not clear the chain.

Giving the user a choice will allow them to tailor the user experience to each circumstance.

**Comment by n288TJYRX** [comment]
I think this is done already, there's a button "Reset operation chain" that resets it. At the moment by default clicking "Execute operation chain" doesn't reset the chain.

**Comment by d47853** [comment]
Basically you need to add a switch in the settings to reset the chain when an operation completes.

Then when results are returned from an operation chain, the setting needs to be checked and if set to true, needs to reset the chain.

**Comment by n288TJYRX** [comment]
Hi I'm having problems with the UI. When I make a change it doesn't seem to update in the browser when I refresh it. Chrome seems better and seems to update most of the time but Firefox is really bad and is still showing elements on the UI that I added back when I was on a different branch, it just doesn't seem to update. Is there a particular browser we should be using? Is it not compatible with all browsers? Sometimes I can even connect to the UI on localhost when the script hasn't finished running.

**Comment by d47853** [comment]
Ah yeah, I've had this issue before. To get around it I use Chrome and press F12 to bring up developer options, then long press the refresh button until "empty cache and hard reload" appears.

**Comment by n288TJYRX** [comment]
Okay I've got a checkbox and it clears the chain when its checked. But I just can't figure out how to make it stay checked when navigating away from the query page and back again.
`
            <md-checkbox ng-model="ctrl.clearChainAfterExecution" ng-checked="ctrl.clearChainAfterExecution" on-change="ctrl.saveClearChainCheckState()">
                    Clear Chain After Execution
            </md-checkbox>

    vm.clearChainAfterExecution = JSON.parse(localStorage.isClearChainChecked);
    vm.saveClearChainCheckState = function() {
        localStorage.setItem("isClearChainChecked", JSON.stringify(vm.clearChainAfterExecution));
        console.log(vm.clearChainAfterExecution);
    }
`

**Comment by d47853** [comment]
It may be worth moving this component into the settings page (where the operation limit lives). Then you could use the settings service to save the state.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
