### ISSUE TITLE
Make Named Operation parameters appear in vertical list

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#536]
Wrapping the Named operation parameters means that space is wasted in the UI. For Named views, this parameter wrapping is okay because of the limited space available. However for Named operations, we should use a vertical layout as this creates a more natural flow for the user.

**Comment by twisted-sres** [comment]
Hey, I would like to work on this issue.

**Comment by d47853** [comment]
Go for it!

**Comment by n288TJYRX** [comment]
Hi, I'd like to try this.

**Comment by n288TJYRX** [comment]
I have the road traffic example ui loaded up but there are no named operations for this. How do I get a named operation so I can see what the UI currently looks like for named operations. Is there another ui script I can run that has named operations? Otherwise #288 needs completing first.

**Comment by d47853** [comment]
You can add a named operation via the REST service (which is hosted at localhost:8080/rest when you run the start script).

There's some examples of NamedOperations in the docs:
https://gchq.github.io/gaffer-doc/getting-started/operations/namedoperation.html

**Comment by d47853** [comment]
Merged into develop
