### ISSUE TITLE
Primary buttons in the operation chain builder are not obvious

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#537]
Due to the prominence of the Add floating button, attention is taken away from the execute and reset buttons at the bottom of the page. This can be confusing for the user.

To mitigate this, move the buttons closer to the main action area. This will also help with migrating users to the new version of the UI since the reset and execute buttons were previously located in the bottom right hand corner.

**Comment by p013570** [comment]
Merged into develop.
