### ISSUE TITLE
Raw view - enhance or remove

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#575]
Upgrades to the table in the UI have identified the raw view as the new bottleneck when it comes to dealing with large volumes of data (10000+  results). 

Work needs to be done to improve it's handling of large volumes or it could be removed from the UI altogether.

To remove the raw view from the UI, there needs to be a mechanism in place to re-visit, edit and delete previous queries

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
