### ISSUE TITLE
An easy to deploy Gaffer stack

### ISSUE THREAD

**Issue by m316257** [gchq/gaffer-tools#597]
It can be quite complicated to deploy a full Gaffer stack with a store (especially accumulo), rest service, ui etc.

A "Gaffer quickstart" that could deploy a local stack (or on a cloud platform) from a tarball and a couple of scripts would be really useful, particularly for prototyping graphs and learning Gaffer.

**Comment by n3101** [comment]
Quickstart has been developed elsewhere, so this can be closed
