### ISSUE TITLE
Remove duplicate icons

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#599]
Some icons stored under the app/img/material-icons directory are duplicated. Some icons in the material icons directory are also in the img directory and referenced in app/config/icon-config.js. 

Remove the duplicated icons from the parent directory and correct the references.

**Comment by hchho** [comment]
I'd like to take this issue please

**Comment by d47853** [comment]
Thanks for the contribution!

**Comment by d47853** [comment]
Merged into develop
