### ISSUE TITLE
schema-builder add button for json import/export from/to file

### ISSUE THREAD

**Issue by m316257** [gchq/gaffer-tools#60]
On the 'schema' tab in the UI builder it would be good to have a 'save to file' button for each of the 'data schema', 'data types' and 'store types'

The user should be able to specify the path to the file

And similar for uploading a local file.

**Comment by l50741** [comment]
Export is sorted, you can currently import by copying the JSON into the schema fields, but there is no button to upload a file yet.

**Comment by l50741** [comment]
Without a proper backend service uploading files is not really very feasible.
The benefit that would be gained, over opening the file and cut/pasting it, is not worth the added overhead of running a more complicated back-end service.
