### ISSUE TITLE
Remove duplicates from tables

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#615]
For the most part the tables filter out duplicate values. However often you find two of the same element in a table. 

This could be due to the seedMatching property or a different property which is unseen by the end user - so it looks like a duplicate.

Remove these duplicates from the selected elements and the results table

**Comment by c015dariu** [comment]
Hello, I've investigated into this issue utilising the RoadTrafficDemo example and I cannot seem to find any duplicating elements, any that look the same usually have their location value differing which keeps them unique from an end-user perspective as this is also displayed as a row.

Under what circumstances are the values duplicated, as this bug may or may not be already fixed.

**Comment by d47853** [comment]
Hold off on this issue for now, I may need to update the ticket.

Basically it's when you have queried the same edge from both ends. So say you have the graph:

M32 -----------roadHasJunction------------> M32:1

If you run a query for M32 and M32:1, you see two roadHasJunction edges in the results. They appear identical in the table. However when you look at the raw data, the results appear as follows:

```json
{
    "class": "uk.gov.gchq.gaffer.data.element.Edge",
    "group": "RoadHasJunction",
    "source": "M32",
    "destination": "M32:1",
    "directed": true,
    "matchedVertex": "SOURCE",
    "properties": {}
  }
```
and

```json
{
    "class": "uk.gov.gchq.gaffer.data.element.Edge",
    "group": "RoadHasJunction",
    "source": "M32",
    "destination": "M32:1",
    "directed": true,
    "matchedVertex": "DESTINATION",
    "properties": {}
  }
```

**Comment by d47853** [comment]
Okay... so:
For the graph view, we need to ignore the matchedVertex when deduplicating values.

For the table, it appears that we don't do any deduplicating. We should deduplicate the values in the table view, however we want to display the matchedVertex.

**Comment by c015dariu** [comment]
So from what I understand of what you replied, for Graph, I have made changes so that the id for both source and destination flips of an edge are checked to prevent edge duplicates. For Table I have added the matchedVertex column however I am unsure of what you would want deduplicating within the table, from what I've seen, matchedVertex was the only duplicator within the table thus far and adding this column currently makes each unique result actually appear unique to the end user.

**Comment by d47853** [comment]
By submitting repeated operations, you can see the duplicates in the table.

Try searching for 'M32' in the quick query multiple times. You can see the LocationContainsRoad edge appear multiple times (or at least you can on develop)

**Comment by c015dariu** [comment]
Hey, sorry to bother you with another question.

I've managed to eliminate the duplicated values via editing updatefilteredresults however I'm encountering issues regarding when that method is called. If you performed the query and then navigated to the page without selecting the notification, the duplicates are removed, however if you accept the toaster notification and are on the table page (potentially any page) it will show duplicates. Navigating away and to the page returns it back to unique values but I'm unsure on where it is doing this.

Is there some sort of update function the notification performs that bypasses updatefilteredresults? It seems to apply on almost any change to the table data...

**Comment by d47853** [comment]
Nice one. That's rather strange. The notification only navigates to the table page: 
```javascript
// quick-query-component.js
$mdToast.show($mdToast.simple()
                .textContent(text)
                .action('view results')
                .highlightAction(true)
                .position('top right'))
            .then(function(response) {
                if (response === 'ok') {
                    navigation.goTo('results');
                }
            })

// navigation-service.js
navigation.goTo = function(pageName) {
        if(pageName && common.startsWith(pageName, "/")) {
            pageName = pageName.substr(1);
        }
        currentPage = pageName;
        $location.path('/' + pageName);
        events.broadcast('routeChange', [currentPage]);
    }
```
I would guess it's something to do with the $onInit() method in the table - maybe it's destroyed and recreated and that's causing this weird behaviour.

**Comment by c015dariu** [comment]
So it seems the issue was that the results.getResults() was the culprit, the duplication was occuring at the results-service object. After I moved my code to instead deal with the incoming results at the source, it now removes any and all (hopefully) duplicated query data held in the Gaffer UI.

Just need to tidy it up and add some comments.

**Comment by d47853** [comment]
Merged into develop
