### ISSUE TITLE
Refactor graph configuration

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#616]
Allow other Cytoscape graph properties to be configured in the UI. Graph properties include things like the layout, animation etc.

Currently, all of the default configuration is located in the graph component. It should be moved out into the defaultConfig.json file. This would mean the merge logic can be deleted from the graph component.

**Comment by g609bmsma** [comment]
Anyone mind if I take this one? Currently as far as I can see it's a simple matter of moving the stuff in 'configuration' in `graph-component.js` to `graphConfig.json` and adding in the quotation marks where needed. After that, all that needs doing is changing lines 111 and 117 of `graph-component.js` to match line 114.

**Comment by d47853** [comment]
Do you mean defaultConfig.json?

Basically it's just removing the default configuration from the graph component (and schema component) into the configuration file so that admins can better determine the behaviour of the graph.

The schema view will also need updating to use the new configuration (it uses the same graph configuration to draw the schema).

The schema uses the schema-view-service.js file to draw the graph.

**Comment by g609bmsma** [comment]
You're quite right, I did mean `defaultConfig.json`.

I've moved the configs from `graphcomponent.js` and `schema-view-service.js` into `defaultConfig.json`, and now import that as their configurations, but the graph and schema are now both coming up blank. Will take a further look at why this is, but any ideas why would be appreciated.

**Comment by d47853** [comment]
I can't see your branch but is there an error in the console?

**Comment by g609bmsma** [comment]
No problem, fixed the issue, just needed to put the config in a different part of the json

**Comment by g609bmsma** [comment]
Hi there, just wanted to bring an update. Ran the start script again on Monday and found the graph doing the same issue of not displaying the schema or the graph. I can't find any errors in the console at all, all seems to compile fine and all results are shown in the table tab. I also seem to be able to access the page whilst the script is not running - I can't perform any queries or get results, but the page loads in a browser. Is it a browser issue?

**Comment by g609bmsma** [comment]
I've now found a resolver for the loading issue (issue #481 comment with dev tools in chrome and Erase cache reload was the solution) and now, with my current solution, I have the tools and space where the graph/schema should be loading. The graph itself does not load, and the schema is replaced by a simple schema, with the only error on both pages being:
`TypeError: Cannot read property 'style' of undefined at generateStylesheets (graph-component.js:200) at graph-component.js:104`
Any advice on getting rid of this?

**Comment by d47853** [comment]
It's hard to tell exactly without seeing the code but looks like you're passing an undefined value somewhere. I'd step through the code using the browser to get more detail.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
