### ISSUE TITLE
Investigate autocomplete operation selector

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#619]
Sometimes (often after deleting an operation), the autocomplete comes up with a blank box (ie not displaying the operations and their descriptions).

**Comment by g609bmsma** [comment]
Hi, I've been having a look/investigate of this error and I can't seem to duplicate this error - the autocomplete box always has options in, no matter how many times I have deleted other operations in a chain. Are there any more details I could use to try and find the cause/circumstances?

**Comment by d47853** [comment]
So I get it when I load in an operation from the "Previous queries" page, then highlight the select operation autocomplete field by clicking it and deleting the text.

**Comment by d47853** [comment]
There's no errors in the logs and the options come back once text is inputted so it's not the end of the world - just a slight annoyance

**Comment by g609bmsma** [comment]
Having done a bit of rooting around in other md-autocomplete issues, [this one seems most like this issue](https://github.com/angular/material/issues/4469):

> Steps:
> 
> 1. Click md-autocomplete field
> 2. Select any suggestion
> 3. Click reset from the end of the field
> 4. Click md-autocomplete field
> 
> Expected outcome:
> I get list of suggestions like in the beginning.
> 
> Actual outcome:
> Suggestions not showing up. I have to click outside md-autocomplete field and then click back inside the field to get suggestions."

This ended up being an issue with the version of Angular being used, and was an issue they had solved, [as seen here](https://github.com/angular/material/pull/4958).

Not a solution as yet, but definitely something related I think? Solution could be either to use a more up to date/different version of Angular, or maybe to look into their fix and find what was added and see if we can use it to fix our issue

**Comment by d47853** [comment]
There's no reason we can't update

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
