### ISSUE TITLE
Fix rejection errors

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#621]
Stop possibly unhandled rejection errors being logged to the console when quick queries are sent. Does not seem to interfere with UX.

**Comment by c015dariu** [comment]
Hello, I had a quick look into this issue and seem to be able to reproduce the unhandled rejection usually by quickly querying something like "car" then "Car" then "bus", "Bus"... etc. and it will then appear in the console. Unfortunately the errors lead into the angular library and I'm unable to see any further as to where the issue emanates from. I've had a look at the quick-query component however it seems to already have some form of error handling around it.

Any advice on where else to look?

**Comment by d47853** [comment]
When I look at the error, I see quite a lot of $mdToast mentioned. This bug is probably related to the call to the toast service to bring up the "n results returned" message.

**Comment by c015dariu** [comment]
So I managed to find the issue causing the error printing which is to do with Angular now pushing any potential unhandled promises to the console as errors however I've noticed it is very easy to break the quick query bar by rapidly entering in random seeds, this ends up with it always returning 0 results or my implemented error dialog using toast. Get All Elements still works however.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
