### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#626]
Add a favicon.ico to the UI to stop errors in the console.

**Comment by medha-yadav** [comment]
Hey I would like to do this.

**Comment by d47853** [comment]
Sounds good. You'll need to create a fork and submit a pull request.

Here's a summary of our contribution guidelines: https://github.com/gchq/Gaffer/blob/master/README.md#contributing

**Comment by d47853** [comment]
I think the REST API has a favicon, so you could probably just steal that one

**Comment by c015dariu** [comment]
Hey, if this still hasn't been done yet, I think I can quite quickly tackle this

**Comment by medha-yadav** [comment]
Sure you can do it.
Sorry for delay from my side.

**Comment by d47853** [comment]
Merged into develop
