### ISSUE TITLE
Tables with large number of columns are more difficult to scroll

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#627]
When the number of results grow, it can make the table scrollable. In order to scroll the table, the user has to go to the bottom of the table and scroll across.

The scrolling should be simpler - so the user can scroll horizontally regardless of where their mouse is. 

Alternatively the table could be made smaller by default (~15 rows) however this does not solve the problem if the user wants to compare more rows.

**Comment by n288TJYRX** [comment]
I've wrapped the table in a div with a class and added some code that listens for the user clicking down on the table and then gets how much their mouse has moved and then scrolls the table based on that. But It doesn't seem to change the divs scrollLeft property which is fixed at 0 even after typing this.scrollLeft = 100.

In table.html I have
'''
<md-table-container>
        <div class="box drag">
            <table md-table id="results-table" class="compact">
            ...
            </table>
        </div>
</md-table-container>
'''
I've added this into table-component.js 
'''
    var elementScroll = document.querySelector('.drag');
    var mx = 0;
    
    elementScroll.addEventListener("mousedown", function(e){
      this.sx = this.scrollLeft;
      mx = e.pageX - this.offsetLeft;
      this.addEventListener("mousemove", mouseMoveFunction);
    });
    
    elementScroll.addEventListener("mouseup", function(e){
      this.removeEventListener("mousemove", mouseMoveFunction);
      mx = 0;
    });
    
    function mouseMoveFunction(e) {
      var mx2 = e.pageX - this.offsetLeft;
      if (mx) {
          this.scrollLeft = this.sx + mx - mx2;
      }
    }
'''
To styles.css I've added 
'''
*{box-sizing:border-box; -webkit-box-sizing:border-box;}
html, 
body {
    height: 100%;
    margin: 0;
  font-family: Roboto,"Helvetica Neue",sans-serif;
}
.box {
  overflow-x: auto;
  overflow-y: hidden;
  width: 500px;
  margin:60px;
  -webkit-touch-callout: none;
  -webkit-user-select: none;  
  -moz-user-select: none;   
  -ms-user-select: none;     
  user-select: none; 
}
table {
  width: 100%;
}
table td,
table th {
  padding: 5px;
}
'''

**Comment by n288TJYRX** [comment]
Okay you can now drag and scroll the table but the header doesn't stay fixed. I'm thinking of trying https://github.com/daniel-nagy/fixed-table-header#license which uses an MIT License. Is this okay to use?

**Comment by d47853** [comment]
Yeah, it's okay. Just make sure you update the NOTICES file

**Comment by n288TJYRX** [comment]
Okay managed to do it without that module in the end.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
