### ISSUE TITLE
Move schema view to component

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#629]
The Schema View should live in a component rather than a service. It should be refactored to make it more supportable. 

Since schemas tend to be small (in terms of number of vertex types and edges), there doesn't tend to be much (if any) performance hit from doing it the current way, it's just more difficult to build upon. It should be done similar to #574. This is mainly for the benefit of developers in the event that we want to build on this capability.

It would also allow us to add more unit tests which should be included as part of this issue.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
