### ISSUE TITLE
Optionally disable hiding of operation options

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#631]
When you use a small number of operation options, the hiding of operation options can be more of a hindrance than a help. 

The idea behind hiding operation options was that in the event of a store or graph using lots of these options, you could hide up some by default to avoid taking up lots of room on the screen.

However, if a user double clicks the clear button by mistake, they could accidentally hide the option.
There should be a way of disabling the hiding of operation options. 

This could be done by adding a simple flag in the configuration which disables hiding of the options.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
