### ISSUE TITLE
Remove md-select-on-focus property from parameters

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#634]
The property causes parameters and configuration to be auto-selected. This is annoying for users who want to make minor changes to properties as they have to click multiple times or risk overwriting the property entirely.

Remove the property from the dynamic input template to resolve the issue.

**Comment by g609bmsma** [comment]
Hi, would anybody mind if I had a go at this one?

**Comment by d21211122** [comment]
@g609bmsma - go for it.

**Comment by d47853** [comment]
Merged into develop
