### ISSUE TITLE
ServicePortal

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/gaffer-tools#636]
The ServicePortal is responsible for creating/spinning up stores from an AddGraph operations from a user. The ServicePortal then returns the endpoint/UI/address to the user. The user will then use this link to go off and interact with the new store, interaction/queries with the new store does not occur through the ServicePortal.

The ServicePortal will be an implementation of the proxy store. The proxy store has an internal representation of the graphs the ServicePortal has created/knows about. This GraphOfGraphs is a representation of the ecosystem of graphs, users, roles, access etc etc... and can be queried and used like any other graph.

The ServicePortal delegates operations it receives to the proxy graph (GraphOfGraphs), unless the ServicePortal detects operations within the opchain that the servicePortal has an operationHandler for.
This allows (similar to a hook) the service portal to handle/intersect operations.
The ServicePortal will have an AddGraphHandler, this handler will create elements such as a "graph" entity and "canAccess" edge etc etc...  and then execute an addElements operation to the GraphOfGraphs. Meanwhile it will also kick of an job to actually create the new Store.

-------------------
### Update

No longer a new store, but configured ProxyStore with no CoreOperations, with a set of ServicePortal orientated handlers such as AddGraphHandler.

**Comment by d21211122** [comment]
The store would basically be that service. It would just be a simple proxy store that adds additional handlers for those custom operations, so existing stores don't need to support them.
There are some use cases where implementing the service as a store would be beneficial - such as allowing federated stores to proxy back to the portal to allow creation of new graphs as part of an operation chain.

**Comment by d47853** [comment]
Couldn't we just add the operations to an existing store using the OperationDeclarations file?

**Comment by t11947** [comment]
I believe this issue is now covered by the Kai project - github.com/gchq/kai, as such this issue can be closed.
