### ISSUE TITLE
Automatically add arrows to edges if they are directed

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#637]
Currently a user has to use the UI config to set the edge arrow shape for edges in the graph view (can be set to none for undirected edges).

We could make this automatic so that Admins don't have to add this to every undirected edge in the UI.

This would also help admins who don't want to configure the UI.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
