### ISSUE TITLE
Integration tests failing when run on AWS

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-tools#645]
`Tests Run: 349, Failures: 0, Errors: 73, Skipped: 0`

**Comment by ctas582** [comment]
In the Maven test output we are seeing a bunch of `BAD_AUTHORIZATIONS` errors:
```
shouldGetAllElements[0: Full Schema](uk.gov.gchq.gaffer.hdfs.integration.loader.AddElementsFromHdfsLoaderIT)  Time elapsed: 0.103 sec  <<< ERROR!
java.lang.RuntimeException: org.apache.accumulo.core.client.AccumuloSecurityException: Error BAD_AUTHORIZATIONS for user gaffer_test on table integrationTestGraph(ID:2f) - The user does not have the specified authorizations assigned
```

On the Accumulo Tablet Servers, we are seeing:
```
uk.gov.gchq.gaffer.data.elementdefinition.exception.SchemaException: Failed to load element definitions from bytes
Caused by: uk.gov.gchq.gaffer.exception.SerialisationException: io/github/classgraph/ClassGraph (through reference chain: uk.gov.gchq.gaffer.store.schema.Builder["types"]->java.util.LinkedHashMap["json"]->uk.gov.gchq.gaffer.store.schema.TypeDefinition["class"])
Caused by: java.lang.NoClassDefFoundError: io/github/classgraph/ClassGraph
```

**Comment by ctas582** [comment]
NoClassDefFoundErrors on Accumulo Tablet servers have been fixed by gchq/gaffer#1996

[ParameterizedLoaderIT.java](https://github.com/gchq/Gaffer/blob/bfc47979922c961f545076ee352cbb6f38314e99/integration-test/src/test/java/uk/gov/gchq/gaffer/integration/impl/loader/ParameterizedLoaderIT.java#L63) in the Gaffer repo requires the Accumulo user that tests are run with to be able to apply the visibility called 'private', which is the cause of the `BAD_AUTHORIZATIONS` errors - 76568f99008c24314d339652e9aac21a4bac5fef addresses this.

**Comment by ctas582** [comment]
Tests now continuing to fail because [AddElementsFromHdfsLoaderIT.java](https://github.com/gchq/Gaffer/blob/f0475872841d2bc547a4d59fb5a6053f19c426f2/library/hdfs-library/src/test/java/uk/gov/gchq/gaffer/hdfs/integration/loader/AddElementsFromHdfsLoaderIT.java#L200) is hard-coded to use a local HDFS instance.

**Comment by d47853** [comment]
Merged into develop
