### ISSUE TITLE
Allow a global operation option to be set via a url parameter

### ISSUE THREAD

**Issue by p013570** [gchq/gaffer-tools#679]
In the UI operations and seeds can be set via a URL parameter. It would also be useful to be able to set an operation option via a url parameter. Specifically, so that a graphId option could be set when used with the federated store. The option that needs setting is the one on the settings page. After setting the option, it needs to trigger the update schema mechanism.

**Comment by n288TJYRX** [comment]
I'll have a go at this

**Comment by n288TJYRX** [comment]
So are there two issues here? 
 - You want to be able to automatically fill the options for operations on the query page through the URL.
 - And also to be able to fill the graphID options on the settings page through the URL and then reload the schema.

**Comment by d47853** [comment]
I think the latter option. However I think for this to be an effective feature, it should not require the user to go to the settings page for this to take effect.

The URL should also be updated if the options are changed by the user

**Comment by n288TJYRX** [comment]
I'm no longer working on this, If someone else wants to take over they are free to do so.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
