### ISSUE TITLE
operation url parameter does not work

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#681]
The operation parameter eg:
`http://gaffer:8080/ui/#!/query?op=GetElements&input=mySeed` doesn't really work when using an operation chain.

We need a way of sharing operation chains via the URL. The URL should also update when the chain updates so that users may share their chains with each other.

We should use some kind of encoding or shortening mechanism since the operation chains can be quite complicated

**Comment by n288TJYRX** [comment]
When you say using operation parameters doesn't really work, are you referring to the fact that you have to click on the input before the operation and parameter are inserted and appear?

**Comment by d47853** [comment]
I mean that the URL parameters aren't updated when the input gets updated, You may want different inputs in a later operation.

When you use it it just feels really clunky.

**Comment by n288TJYRX** [comment]
I'm using pushState() from the $window service to update the URL without reloading the page, but after it exits my function updateURL() the component seems to get reloaded and what I've started typing disappears, I don't know why. I feel like my code works, but something else is listening in for a change in the URL (popState event I think) and then doing stuff based on that. I think it might be angularJS itself.

**Comment by n288TJYRX** [comment]
At the moment my idea is to save the whole operation chain using the vm.operations in operation-chain-component.js and be able to set this when passing an operation chain through the URL.

**Comment by n288TJYRX** [comment]
I'm no longer working on this, If someone else wants to take over they are free to do so.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
