### ISSUE TITLE
Update Copyright script to include README.md files

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#683]
README.md files currently read '2016' where it should be '2016-2019' like all the other files.

Update the script located at `./cd/updateCopyrightHeaders.sh` and files to show the updated header.

**Comment by jatinkumarg** [comment]
Hey, can I work on this issue?

**Comment by SupreethBaliga** [comment]
Hi. I would like to take this up.

**Comment by n3101** [comment]
This issue was in fact fixed later by the reporter and merged in https://github.com/gchq/gaffer-tools/pull/864.
