### ISSUE TITLE
Table and charts sort numbers alphabetically

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#684]
Numbers are sorted alphabetically which results in strange tables and charts.
ie: 1, 13, 2 rather than 1, 2, 13

The table should sort them numerically.

The documentation for the data table we use is located [here](https://github.com/daniel-nagy/md-data-table#numeric-columns):

**Comment by c015dariu** [comment]
Hey, @d47853 

Can you tell me in what conditions these sorting errors appear? I had a go at messing with the table but so far they all sort numerically.

**Comment by d47853** [comment]
In the road traffic demo, the cardinalilties (hllp) property is sorted incorrectly.

**Comment by c015dariu** [comment]
So it appears shortValue() converts HLLP cardinality into a string for some unknown reason. I've rectified this by bypassing that function when it parses HLLP objects. It would most likely be better if shortValue() can be adjusted to instead return an integer for the cardinality however I'm unsure if whether it must be a string for the rest of the application to function?

**Comment by d47853** [comment]
Not that I can think of. That seems sensible

**Comment by d47853** [comment]
Merged into develop
