### ISSUE TITLE
Create script for applying jackson shading to a jar

### ISSUE THREAD

**Issue by p013570** [gchq/gaffer-tools#69]

**Comment by t616178** [comment]
Merged into develop

**Comment by p013570** [comment]
#Migration Steps
Before added the iterator jars to accumulo you should run [jar-shader](https://github.com/gchq/gaffer-tools/blob/master/jar-shader/shade.sh) against all the jars. This will shade the jackson version and force Accumulo/Gaffer to use the correct version. Without this you may come across issues on clusters using CDH. This is linked to issue gchq/Gaffer#749 and gchq/Gaffer#722.
