### ISSUE TITLE
Cleaner example for your README.md.

### ISSUE THREAD

**Issue by okram** [gchq/gaffer-tools#7]
In your README, you have:

```
start = '1'; end = '3'; g.V(start).hasLabel('id').store('v').repeat(bothE().where(without('e')).store('e').inV().hasLabel('id').where(without('v'))).until{it.get().id() == end || it.loops() == 6}.path().filter{it.get().last().id() == end}
```

This can be written without lambdas and bit cleaner as:

```
g.V('1').hasLabel('id').
  repeat(bothE().otherV().hasLabel('id').simplePath()).
    until(hasId('3').or().loops().is(6)).
  hasId('3').path()
```

Things to note:

1. You don't need to store "v" and "e" as `simplePath()` will ensure you don't go back to an already seen edge/vertex.
2. You don't need lambdas in your `until()`.
3. If the end of the path must have an id of `end`, then simply `hasId(end)`.
4. `bothE().otherV()` goes in both directions. If you don't care about the edges in your final path data structure, just use `both()`.
5. If you want to be fancy, you could do `...path().by('name')` and that would return the path where instead of the vertices, you would have `name` properties from those vertices. Easier for the human to read the result. http://tinkerpop.apache.org/docs/current/reference/#path-step

**Comment by p013570** [comment]
Thanks for you're help - that looks quite a bit neater! 

If you would like to raise a pull request to make these changes yourself, then you just need to agree to our [OSS Contributor License Agreement](https://github.com/gchq/Gaffer/wiki/GCHQ-OSS-Contributor-License-Agreement-V1.0). 

Alternatively we can update README with your suggestion.

**Comment by okram** [comment]
Please feel free to just update the README yourself for now. Moving forward I will provide PRs. Thank you.

**Comment by p013570** [comment]
Merged into develop.
