### ISSUE TITLE
Add Federated Store helpers to operations

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#704]
The way graph ids are added to operations is unintuitive for most python users. Rather than having to add a dict for the options with a complicated key, most expect relevant variables to exist on the operation they are running.

So instead of:
```python
g.GetAllElements(options={
  "gaffer.federatedstore.operation.graphIds": "myGraph,myOtherGraph"
})
```
There should be something like
```python
g.GetAllElements(options=["myGraph", "myOtherGraph"])
```

**Comment by j8934893** [comment]
Is it safe to assume that anything passed into the options parameter is going to be a graphId?
I have never used it for anything else but wanted to check.

For example - https://github.com/gchq/gaffer-tools/blob/develop/python-shell/src/test/test_gaffer_operations.py#L4377-L4379 - passes a key-value dict. I assume this is just to illustrate the structure?

**Comment by j8934893** [comment]
Done some digging and it sounds like the options flag is being used for things other than graphIds.

I wonder if it would be worth adding an additional parameter to the Operation class "graph_ids" that would accept a list input and under the hood would build the options param with the federated store key.

That would make it easier to read, whilst retaining the other options functionality. Not sure if it is overkill adding another param to that class (and all the classes that super() it) though.

**Comment by t92549** [comment]
I think this is indicative of a larger problem with gafferpy like you said, where python users don't expect to need to provide a dictionary with java classes as keys. This goes both ways, where results are dictionaries with single java class keys before the result.
I will try to tackle both of these issues in fishbowl where this is more freedom to make breaking changes to the api.

One way perhaps to make this more generic would be to provide a `**kwargs` argument as well as the other parameters that gets interpreted by the Operation class. If for example someone then used:
```python
g.GetAllElements(federated_graph_ids=["myGraph", "myOtherGraph"])
```
Then the operation class could pick it up, match the `federated_graph_ids` key with `"gaffer.federatedstore.operation.graphIds"` and then insert that into the options dict.

@j8934893 If that sounds good then perhaps #869 could be updated to reflect this?

**Comment by t92549** [comment]
Having actually looked again, like @j8934893 said, it would be a lot of hassle and code change to add additional parameters to every gafferpy operation. This would be a nice feature for the future in fishbowl, but I think for now the solution in #869 is okay.  If a normal options dict is passed in it will still work, but if a list is passed in it presumed you are providing what is probably the most common use case for options, federated graph ids.
I will approve and merge once @j8934893 confirms they are happy with it.
