### ISSUE TITLE
Add AccumuloStoreITs to run as part of gaffer-slider IT suite

### ISSUE THREAD

**Issue by ctas582** [gchq/gaffer-tools#71]
#52 only runs AbstractStoreITs against a gaffer-slider instance.
We should also run AccumuloStoreITs.
Doing this requires gchq/Gaffer#686 to be fixed.

**Comment by n3101** [comment]
gaffer slider is being withdrawn (https://github.com/gchq/gaffer-tools/issues/968) so this won't be done.
