### ISSUE TITLE
Add option to rename and add descriptions to queries

### ISSUE THREAD

**Issue by p013570** [gchq/gaffer-tools#790]
These names and description would then be displayed on the 'My queries page'. At the moment a big list of "Get Elements" queries isn't very useful.

**Comment by jpelbertrios** [comment]
Do we need to show Dialogbox when user edit the name and description, same like Dialogbox showing for save opration chain

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
