### ISSUE TITLE
Improve the zooming on the graph UI

### ISSUE THREAD

**Issue by p013570** [gchq/gaffer-tools#793]
Currently when you zoom in/out of the graph in the UI, it jumps between resolutions. Often this means the resolution ends up being too big or too small. Users want to have finer control over the zoom level.

**Comment by dro-1** [comment]
Can I work on this issue

**Comment by p013570** [comment]
@dro-1 - yeah that would be great, thanks. I think the change is fairly simple, it is just adding a wheelSensitivity setting in the graph_component.js file. It needs to be added to the configuration variable on line 56 ish. Perhaps a setting like: "wheelSensitivity: 0.3" would work quite well. It would be good to get this change merged in soon.
