### ISSUE TITLE
Column selection in the table view gets confused when you delete a column

### ISSUE THREAD

**Issue by p013570** [gchq/gaffer-tools#795]
To replicate a common issue do the following on the Road Traffic Example:

GetElements: M5:11
Go to table view and delete the edgeGroup column.
Clear results
GetElements: M5
Go to table view
The previous columns like hllp are still there even though there is no data for them. The Choose columns drop down doesn't have the extra columns like hllp in it.

I'm not sure what the best solution is, but the table view doesn't get quite confusing when you do multiple queries, each returning different property names.

**Comment by jpelbertrios** [comment]
Given I have made a search according to instructions 
When I delete the column and clear results
And test with M5 
Then I am unable to find empty column in table view

Is there any other scenario which I can check and Are they expecting tests to be written with implementation?

**Comment by d47853** [comment]
Yeah I'd expect the hllp and edgeGroup fields to be present because they are properties of the M5 entity.

**Comment by t11947** [comment]
I also couldn't replicate this. The dropdown had the expected columns and as @d47853 says, the hllp and edgeGroup fields are properties of the M5 entity and so have values for this result.

**Comment by jpelbertrios** [comment]
ok..is there anything I can look for this ticket ?

**Comment by t11947** [comment]
> ok..is there anything I can look for this ticket ?

I'd wait for @p013570 to elaborate before continuing.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.

**Comment by n3101** [comment]
The UI fails to meet our Accessibility policy. It is unmaintainable and will be removed shortly.
