### ISSUE TITLE
Possible Security Problems

### ISSUE THREAD

**Issue by ctindall** [gchq/gaffer-tools#804]
Hey there! I noticed some possible problems in some code in this repo. A quick summary of a few of them is below, but let me know if you're interested in seeing a full report or talking about cloud security in general.

---

**severity:** serious

**filename:** `./deployment/aws/core/cloudformation/gaffer-slider-emr.yaml`

**line number(s):** [183, 192, 202, 212, 222]

**resource(s):** 

Missing egress rule means all traffic is allowed outbound.  Make this explicit if it is desired configuration

---

**severity:** warning

**filename:** `./deployment/aws/core/cloudformation/gaffer-slider-emr.yaml`

**line number(s):** [370]

**resource(s):** 

IAM role should not allow * resource on its permissions policy

---

**severity:** warning

**filename:** `./deployment/aws/core/cloudformation/gaffer-slider-emr.yaml`

**line number(s):** [497]

**resource(s):** 

S3 Bucket should have access logging configured

---

**severity:** warning

**filename:** `./deployment/aws/core/cloudformation/gaffer-slider-emr.yaml`

**line number(s):** [497]

**resource(s):** 

S3 Bucket should have encryption option set

---

**severity:** warning

**filename:** `./deployment/aws/core/cloudformation/gaffer-with-user.yaml`

**line number(s):** [181]

**resource(s):** 

S3 Bucket should have access logging configured

---

**severity:** warning

**filename:** `./deployment/aws/core/cloudformation/gaffer-with-user.yaml`

**line number(s):** [181]

**resource(s):** 

S3 Bucket should have encryption option set

---

**severity:** warning

**filename:** `./deployment/aws/core/cloudformation/gaffer-with-web.yaml`

**line number(s):** [243]

**resource(s):** 

S3 Bucket should have access logging configured

**Comment by ctas582** [comment]
Hi, thanks for taking a look at our CloudFormation code. The S3 buckets that are provisioned are only used to temporarily store copies of artefacts available in our GitHub repo, so I'd consider not having encryption or access logging as a minor issue. However, adding encryption can't hurt. Are you interested in submitting a PR?

**Comment by n3101** [comment]
This appears to have gone away.
