### ISSUE TITLE
Analytics UI: bad routing on home page

### ISSUE THREAD

**Issue by c95560** [gchq/gaffer-tools#823]
Automatic redirect from home page to /analytics is not working.

When you go to the home page no analytics are shown, only a grey content area is shown. Clicking on the home button works as intended: it redirects you to /analytics and displays the analytic cards.

Suggest moving the /analytics cards to display on the host root URL rather than fixing the redirect: redirects introduce additional page load latency.

**Comment by b492ddo** [comment]
I'll claim this one.
