### ISSUE TITLE
Analytics UI: CSS padding / positioning / display styling on results table

### ISSUE THREAD

**Issue by c95560** [gchq/gaffer-tools#824]
A couple of CSS bugs:

 1. When displaying a large number of results from an Analytic, the table takes up the full extent of the visible vertical scroll. Consequently the pagination buttons / dropdowns below the table are no longer visible.
2. Indentation looks broken. HTML elements on the edge of the view port.

**Comment by b492ddo** [comment]
I'll claim this one.

**Comment by c95560** [comment]
Closed due to redundancy
