### ISSUE TITLE
Analytics UI: query input field restrictions too loose / input errors do not give any feedback

### ISSUE THREAD

**Issue by c95560** [gchq/gaffer-tools#825]
e.g. select an an analytic, set the input field "maximum results" to -1. When you perform a query the spinner will display, but nothing else will happen: the user may potentially be expecting results.

Suggest twofold fix (using maximum results as an example, but may apply to other input field types):
1. When the backend returns an error message the user needs to be notified in some manner. e.g. error message is displayed on query page with red text. A generic message like "Invalid Query Input" would be sufficient. A more specific error would be better, e.g. "maximum results input field must be positive" - do not display an unprocessed stack trace returned from the backend: the error should be easily readable for non technical users.
2. Tightening input requirements using pattern validation. 

e.g. for positive integer text input to display a green field background when valid, red when invalid:
```
<style>
input:invalid {
	background-color: red
}
input:valid {
	background-color: green
}
input:placeholder-shown {
    background-color: white
}
</style>
<input type="text" id="maximum_results" name="maximum_results" pattern="^[1-9][0-9]*$" title="Must be a positive integer greater than 0" placeholder=" ">
```

**Comment by b492ddo** [comment]
I'll claim this one.

**Comment by c95560** [comment]
Closed due to redundancy
