### ISSUE TITLE
Update Default value of Accumulo version in AWS deployment

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#826]
In the next version of Gaffer (1.12.0), the accumulo version will be bumped to 1.9.3. Update the default version in deployment/aws to reflect this.

**Comment by t11947** [comment]
I believe the default values of some of the other dependencies could be updated also. Gaffer for example.

**Comment by r32575** [comment]
I have updated gaffer, gaffer-tools and accumulo versions on the gh-826 branch. Take a look and let me know if they are correct.

**Comment by d47853** [comment]
Merged into develop
