### ISSUE TITLE
Replace references to MockAccumulo with MiniAccumulo

### ISSUE THREAD

**Issue by t11947** [gchq/gaffer-tools#831]
Replace references to MockAccumulo with MiniAccumulo. This change will set us up to move to Accumulo 2.X in the future. There may be some significant refactoring required as a 1-1 replacement will likely slow down the tests significantly, and so store reuse is encouraged.

Linked to https://github.com/gchq/Gaffer/issues/1836

**Comment by t92549** [comment]
Resolved due to #876
