### ISSUE TITLE
UI tests failing due to node compatibility issues

### ISSUE THREAD

**Issue by t11947** [gchq/gaffer-tools#833]
Presently, travis is using the latest version of nodejs to run the testing suite on for the UI apps. This has caused compatibility issues, as reported here: https://github.com/gchq/gaffer-tools/pull/830.

Changing Travis to use the LTS version of node should prevent these issues.

**Comment by n3101** [comment]
@t92549 ref the node version change you mentioned this am, has this issue now gone away?

**Comment by t92549** [comment]
This was potentially fixed in travis by #894, but it should not happen anymore as out tests are now on GitHub Actions (#864).
