### ISSUE TITLE
Replace deprecated Authorisation method

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#836]
When updating Github as part of a release, we make use of the Github API. To authenticate we use a Github Token. However the way in which we use the token is deprecated. See here for more detail: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Solution should be the same as the one in Gaffer in Gaffer at https://github.com/gchq/Gaffer/pull/2272

**Comment by mitchell-frost** [comment]
Can I work on this?

**Comment by d47853** [comment]
@mitchell-frost yeah of course

**Comment by d47853** [comment]
Merged into develop
