### ISSUE TITLE
Python shell GetWalks with non GetElements operation gives strange error message

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-tools#851]
GetWalks only supports GetElements operations in it's operation chain. This is a limitation of the GetWalks operation. If you try and use another operation, the GetWalks operation will fail with validation errors with a helpful error message. However if you try to compile a GetWalks with no GetElements operation with the python shell, you get a non-descriptive Json serialisation error. This is due to the following code:
```python
if operations is not None:
            self.operations = []
            for op in operations:
                if not isinstance(op, GetElements) and not isinstance(op, OperationChain):   # This is the line that breaks everything
                    op = JsonConverter.from_json(op)
                self.operations.append(op)
```
Essentially, if the operation is anything other than GetElements or OperationChain, it tries to json deserialise it. Therefore if you try and use GetAdjacentIds, it fails as the object is not a deserialisable string. The python shell should either handle this and provide a more descriptive error message or (more preferably) just pass the operations to the REST API and let Gaffer handle it. The reason I'd prefer it done the latter way is that it allows us to support more operations without changing the python shell.

**Comment by j8934893** [comment]
FYI - You get the same thing when using g.If(), example:
`g.If(
    conditional = g.Conditional(... ),
    then = g.GetAdjacentIds(),
    otherwise = g.Limit(...)
)`

**Comment by t92549** [comment]
> The reason I'd prefer it done the latter way is that it allows us to support more operations without changing the python shell.

Though this method is more maintainable, I decided to go with the former method in my PR #887. This is because the same method of throwing within Python can be found throughout gafferypy and is therefore more consistent. As well as that, the error message can be more user friendly rather than just returning a Java error from Gaffer.
