### ISSUE TITLE
Travis tests failing due to GPG keys

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-tools#881]
See failed test run: https://travis-ci.org/github/gchq/gaffer-tools/jobs/767189161
I am going to make a branch to try and resolve these GPG errors

**Comment by n3101** [comment]
@t92549 Do you know if this was the same error as reported in #417?

**Comment by t92549** [comment]
If it is not the same error then it could maybe be to do with #883. Either way, it was so long ago and no examples are provided it is hard to tell what this is referencing. I had a look through the past builds in travis and couldn't really see anything much failed due to ui tests.

**Comment by n3101** [comment]
@t92549 Fine, I will close #417 as it doesn't tell us anything extra.
