### ISSUE TITLE
Architecture Diagram Visualization

### ISSUE THREAD

**Issue by johspaeth** [gchq/gaffer-tools#889]
Hi @ctas582, 

I just crossed with your repo and saw it uses CloudFormation template, some of which you have been working on. I am developing a tool to visualize data-flows across CloudFormation templates and took the liberty to scan your repo with the tool .

Feel free to take a look at the [following diagram](https://dashboard.codeshield.io/public/result/9b53eab7-e4a8-4506-ae63-f5ba42fa51ab?utm_source=github&utm_medium=shared-graphs&utm_campaign=teamb) and let me know your thoughts on this. I am really interested to get your feedback and to understand if the presented diagram matches the architecture you have in mind.

**Comment by n3101** [comment]
@ctas582 Any thoughts on this?
