### ISSUE TITLE
Typo in SeedMatchingType in python shell

### ISSUE THREAD

**Issue by javadev001001** [gchq/gaffer-tools#94]

**Comment by t616178** [comment]
Merged into develop.

**Comment by p013570** [comment]
I have reverted these changes as they broke the python shell. We really need some automated tests for the python shell, but in the meantime there is an example.py file that you can run to do a basic check of the python functions.

**Comment by p013570** [comment]
I've fixed and merged into develop the typo RElATED -> RELATED that was initially fixed as part of this issue.

**Comment by p013570** [comment]
The result limit works as excepted. I've renamed this issue to just deal with the SeedMatchingType bug.

**Comment by p013570** [comment]
Merged into develop.
