### ISSUE TITLE
Deprecate the schema builder tool

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-tools#947]
The schema builder tool appears not to be used by anyone (no responses received to question in https://github.com/gchq/gaffer-tools/issues/930)  and has not received any development effort in years. 

While a schema builder is in principle a good idea, this implementation isn't the way forward. Deprecate this now for removal in v2.0.

**Comment by t92549** [comment]
I have tried to use it to see if it even works anymore and as far as I can see it doesn't sadly

**Comment by n3101** [comment]
@t92549 So no loss then. Kill!

**Comment by n3101** [comment]
Following a team discussion, it appears that the correct way forward for removing an entire package is to amend its Readme to say that it will be removed in Gaffer 2.0, so please do this.
