### ISSUE TITLE
Remove slider package in its entirety

### ISSUE THREAD

**Issue by n3101** [gchq/gaffer-tools#968]
https://github.com/gchq/gaffer-tools/issues/850#issuecomment-1032350151 identifies that slider relies on a withdrawn package and is incompatible with the recent hadoop versions to which Gaffer will migrate. 

The originator @ctas582 doesn't use it any more and its removal has been announced in https://github.com/gchq/gaffer-tools/discussions/967. 

Remove the slider package from Gaffer 2.0 branch.

**Comment by t92549** [comment]
Closed by #977
