### ISSUE TITLE
Replace direct usages of log4j with slf4j

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-tools#984]
This will enable the change to Reload4j in Gaffer 1.22.0 https://github.com/gchq/Gaffer/pull/2609

**Comment by GCHQDeveloper314** [comment]
Strictly speaking, this isn't a blocker for Gaffer 1.22.0. The import `org.apache.log4j.Logger` is part of Reload4j and would continue to work smoothly with Reload4j. This is still worth doing of course, just not a blocker.
