### ISSUE TITLE
Migrate from Log4j to Reload4j

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-tools#986]
All versions of Gaffer are moving to Reload4j. Some dependencies in Gaffer Tools modules use log4j, which will need to be excluded to prevent a conflict.
This only requires minor POM changes to exclude log4j from some dependencies which use it, [changes will be a smaller version of this](https://github.com/gchq/Gaffer/pull/2609).

**Comment by t92549** [comment]
Closed by #992
